/**
 * LVGL 8.4 Configuration — LawnBot CrowPanel Display
 *
 * Only settings that differ from LVGL defaults are defined here.
 * lv_conf_internal.h provides defaults for everything else.
 */

#if 1  /* required guard — do not remove */

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

/*====================
   COLOR
====================*/
#define LV_COLOR_DEPTH     16   /* 16-bit RGB565 for the LCD */
#define LV_COLOR_16_SWAP    0   /* RGB bytes are NOT swapped (RGB parallel interface) */
#define LV_COLOR_SCREEN_TRANSP  0

/*====================
   MEMORY
====================*/
/* Keep the LVGL heap modest; this UI is simple and the CrowPanel also needs
   DRAM for frame management, WiFi stack, and touch handling. */
#define LV_MEM_CUSTOM       0
#define LV_MEM_SIZE         (96U * 1024U)
#define LV_MEM_ADR          0   /* auto-allocate */
#define LV_MEM_AUTO_OPT     0

/*====================
   TICK
====================*/
/* Use Arduino millis() as the LVGL tick source — no lv_tick_inc() calls needed */
#define LV_TICK_CUSTOM          1
#define LV_TICK_CUSTOM_INCLUDE  <Arduino.h>
#define LV_TICK_CUSTOM_SYS_TIME_EXPR  ((uint32_t)millis())

/*====================
   CUSTOM FONTS
====================*/
/* Large clock font — generated by tools/gen_clock_font.py */
#define LV_FONT_CUSTOM_DECLARE  extern const lv_font_t font_clock_120;

/*====================
   DRAWING
====================*/
/* Required for shadow, gradient, rounded corners, transforms and anti-aliasing */
#define LV_DRAW_COMPLEX 1

/*====================
   DISPLAY REFRESH
====================*/
#define LV_DISP_DEF_REFR_PERIOD  33   /* ~30 fps */
#define LV_INDEV_DEF_READ_PERIOD 30

/*====================
   LOG
====================*/
#define LV_USE_LOG      1
#define LV_LOG_LEVEL    LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF   1

/*====================
   FONTS
   Only Montserrat sizes we actually use are enabled to save flash.
====================*/
#define LV_FONT_MONTSERRAT_12   1
#define LV_FONT_MONTSERRAT_14   1
#define LV_FONT_MONTSERRAT_16   1
#define LV_FONT_MONTSERRAT_18   1
#define LV_FONT_MONTSERRAT_20   1
#define LV_FONT_MONTSERRAT_24   1
#define LV_FONT_MONTSERRAT_28   1
#define LV_FONT_MONTSERRAT_32   1
#define LV_FONT_MONTSERRAT_36   1
#define LV_FONT_MONTSERRAT_48   1

#define LV_FONT_DEFAULT  &lv_font_montserrat_16

/*====================
   WIDGETS
   All standard widgets are ON by default in LVGL v8.
   Extra widgets that depend on disabled base widgets must be explicitly disabled.
====================*/
#define LV_USE_ARC          1
#define LV_USE_BTN          1
#define LV_USE_LABEL        1
#define LV_USE_LINE         1
/* IMG and TEXTAREA must stay ON — extra widgets (animimg, spinbox) depend on them */
#define LV_USE_IMG          1
#define LV_USE_TEXTAREA     1
/* Extra widgets we don't use — disable ALL unused extras to avoid dep chains */
#define LV_USE_ANIMIMG      0
#define LV_USE_CALENDAR     0
#define LV_USE_CALENDAR_HEADER_ARROW    0
#define LV_USE_CALENDAR_HEADER_DROPDOWN 0
#define LV_USE_CANVAS       0
#define LV_USE_CHART        0
#define LV_USE_COLORWHEEL   0
#define LV_USE_DROPDOWN     0
#define LV_USE_IMGBTN       0
#define LV_USE_KEYBOARD     0
#define LV_USE_LED          0
#define LV_USE_LIST         0
#define LV_USE_MENU         0
#define LV_USE_METER        0
#define LV_USE_ROLLER       0
#define LV_USE_SLIDER       0
#define LV_USE_SPAN         0
#define LV_USE_SPINBOX      0
#define LV_USE_SPINNER      0
#define LV_USE_SWITCH       0
#define LV_USE_TABLE        0
#define LV_USE_TABVIEW      0
#define LV_USE_TILEVIEW     0
#define LV_USE_WIN          0
/* Keep these — used by the dashboard */
#define LV_USE_MSGBOX       1

/*====================
   THEME
====================*/
#define LV_USE_THEME_DEFAULT    1
#define LV_THEME_DEFAULT_DARK   1   /* Start in dark mode */

/*====================
   PERF MONITOR (off in production)
====================*/
#define LV_USE_PERF_MONITOR     0
#define LV_USE_MEM_MONITOR      0

#endif /* LV_CONF_H */
#endif /* #if 1 guard */
