"""
tools/gen_images.py
  Converts LawnBot PNG logos to LVGL v8 C arrays (RGB565 + Alpha, 3 bytes/px).
  Removes white backgrounds via flood-fill from corners.

Run from project root: python tools/gen_images.py
"""
import os
from collections import deque
import numpy as np
from PIL import Image, ImageFilter

PROJ   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS  = os.path.join(PROJ, "icons")
SRC    = os.path.join(PROJ, "src")
INC    = os.path.join(PROJ, "include")

# ── Background removal ─────────────────────────────────────────────────────
def remove_white_bg(img, tolerance=22):
    """
    BFS flood-fill from all 4 corners to find background pixels, then
    set their alpha to 0.  Works for logos on pure-white or near-white
    backgrounds without eating light-coloured interior regions.
    """
    img   = img.convert("RGBA")
    data  = np.array(img, dtype=np.uint8)
    h, w  = data.shape[:2]

    visited = np.zeros((h, w), dtype=bool)
    bg_mask = np.zeros((h, w), dtype=bool)

    def is_bg(y, x, ref):
        d = data[y, x, :3].astype(np.int16) - ref
        return bool(np.max(np.abs(d)) <= tolerance)

    q = deque()
    for cy, cx in [(0, 0), (0, w-1), (h-1, 0), (h-1, w-1)]:
        if not visited[cy, cx]:
            ref = data[cy, cx, :3].astype(np.int16)
            if is_bg(cy, cx, ref):
                visited[cy, cx] = True
                bg_mask[cy, cx] = True
                q.append((cy, cx, ref))

    while q:
        y, x, ref = q.popleft()
        for dy, dx in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            ny, nx = y + dy, x + dx
            if 0 <= ny < h and 0 <= nx < w and not visited[ny, nx]:
                visited[ny, nx] = True
                if is_bg(ny, nx, ref):
                    bg_mask[ny, nx] = True
                    q.append((ny, nx, ref))

    data[bg_mask, 3] = 0
    return Image.fromarray(data, "RGBA")


# ── LVGL pixel conversion ──────────────────────────────────────────────────
def to_lvgl_c(img_rgba, var_name, target_w, target_h):
    """
    Resize (maintaining aspect ratio, transparent-padded),
    then encode as LVGL v8 LV_IMG_CF_TRUE_COLOR_ALPHA:
      3 bytes per pixel: [RGB565_lo, RGB565_hi, Alpha]
    Returns (c_source_string, final_PIL_image).
    """
    img_rgba = img_rgba.copy()
    img_rgba.thumbnail((target_w, target_h), Image.LANCZOS)

    canvas = Image.new("RGBA", (target_w, target_h), (0, 0, 0, 0))
    ox = (target_w - img_rgba.width)  // 2
    oy = (target_h - img_rgba.height) // 2
    canvas.paste(img_rgba, (ox, oy), img_rgba)

    a = np.array(canvas, dtype=np.uint16)
    r5 = a[:, :, 0] >> 3
    g6 = a[:, :, 1] >> 2
    b5 = a[:, :, 2] >> 3
    al = a[:, :, 3].astype(np.uint8)

    rgb565 = (r5 << 11) | (g6 << 5) | b5
    lo = (rgb565 & 0xFF).astype(np.uint8)
    hi = ((rgb565 >> 8) & 0xFF).astype(np.uint8)

    # Interleave [lo, hi, alpha] for every pixel
    pixels = np.stack([lo, hi, al], axis=-1).flatten()
    data_size = target_w * target_h * 3

    lines = [
        f"/* Auto-generated by tools/gen_images.py — do not edit. */",
        f'#include "lvgl.h"',
        "",
        f"static const uint8_t {var_name}_map[] = {{",
    ]
    for i in range(0, len(pixels), 16):
        chunk = pixels[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += [
        "};",
        "",
        f"const lv_img_dsc_t {var_name} = {{",
        f"    .header.always_zero = 0,",
        f"    .header.w           = {target_w},",
        f"    .header.h           = {target_h},",
        f"    .data_size          = {data_size},",
        f"    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,",
        f"    .data               = {var_name}_map,",
        "};",
        "",
    ]
    return "\n".join(lines), canvas


# ── Images to generate ─────────────────────────────────────────────────────
IMAGES = [
    # (source filename,                       var_name,          w,   h  )
    ("f01f9637-8c40-49f0-8bf0-d9b28ede5af8.png", "img_logo_splash", 360, 278),
    ("LawnBot_robot_v2.png",                     "img_robot_48",    48,  48 ),
    ("LawnBot_robot_v2.png",                     "img_robot_32",    32,  32 ),
]

header_lines = [
    "/* Auto-generated by tools/gen_images.py — do not edit. */",
    "#pragma once",
    '#include "lvgl.h"',
    "",
]

previews = {}

for fname, var_name, tw, th in IMAGES:
    src = os.path.join(ICONS, fname)
    print(f"  {fname}  ->  {var_name}  ({tw}x{th})")

    raw = Image.open(src)
    clean = remove_white_bg(raw)
    c_src, final = to_lvgl_c(clean, var_name, tw, th)

    out = os.path.join(SRC, f"{var_name}.c")
    with open(out, "w") as f:
        f.write(c_src)

    kb = (tw * th * 3) / 1024
    print(f"    -> {out}  ({kb:.1f} KB in flash)")
    header_lines.append(f"LV_IMG_DECLARE({var_name});")
    previews[var_name] = final

header_lines.append("")
hdr_path = os.path.join(INC, "lawnbot_images.h")
with open(hdr_path, "w") as f:
    f.write("\n".join(header_lines))
print(f"  Header -> {hdr_path}")

# ── Preview PNG: mock the new splash + dashboard header ───────────────────
from PIL import ImageDraw, ImageFont

W, H = 800, 480
preview = Image.new("RGB", (W, H))
dp = ImageDraw.Draw(preview)

# Sky gradient (dark blue)
for y in range(H):
    t = y / H
    r = int(0x06 + t * (0x10 - 0x06))
    g = int(0x18 + t * (0x24 - 0x18))
    b = int(0x2F + t * (0x45 - 0x2F))
    dp.line([(0, y), (W, y)], fill=(r, g, b))

# Paste logo centered
logo = previews["img_logo_splash"].convert("RGBA")
lx = (W - logo.width)  // 2
ly = (H - logo.height) // 2 - 10
preview.paste(logo, (lx, ly), logo)

# "Boise State Edition" subtitle
try:
    f16 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 16)
except:
    f16 = ImageFont.load_default()
dp.text((W//2, ly + logo.height + 14), "BOISE STATE EDITION",
        font=f16, fill=(241, 99, 34), anchor="mt")

out_preview = os.path.join(PROJ, "tools", "preview_splash.png")
preview.save(out_preview)
print(f"  Splash preview -> {out_preview}")

# Dashboard header preview
dash = Image.new("RGB", (W, 72))
dd = ImageDraw.Draw(dash)
for y in range(72):
    t = y / 72
    r = int(0x13 + t * (0x49 - 0x13))
    g = int(0x44 + t * (0xA3 - 0x44))
    b = int(0x88 + t * (0xE0 - 0x88))
    dd.line([(0, y), (W, y)], fill=(r, g, b))

robot = previews["img_robot_48"].convert("RGBA")
dash.paste(robot, (16, 10), robot)

try:
    f24 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 24)
    f12 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 12)
    f14 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 14)
except:
    f24 = f12 = f14 = ImageFont.load_default()

dd.text((72, 14), "LAWNBOT",            font=f24, fill=(248,251,255))
dd.text((74, 46), "BOISE STATE EDITION",font=f12, fill=(241, 99, 34))
dd.text((W-24, 36), "DEMO MODE",        font=f14, fill=(197,210,227), anchor="rm")

out_hdr = os.path.join(PROJ, "tools", "preview_header.png")
dash.save(out_hdr)
print(f"  Header preview -> {out_hdr}")
print("\nDone.")
