"""
gen_clock_font.py
  - Generates include/font_clock_120.c  (LVGL v8 1-bpp font, Arial Bold 120pt)
  - Writes tools/preview_clock.png      (mock-up of the idle screen)
Run from the project root: python tools/gen_clock_font.py
"""
import os, math
from PIL import Image, ImageDraw, ImageFont

FONT_PATH  = "C:/Windows/Fonts/arialbd.ttf"
FONT_SIZE  = 120
CHARS      = "0123456789: "

PROJ       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C      = os.path.join(PROJ, "src",  "font_clock_120.c")
OUT_PNG    = os.path.join(PROJ, "tools","preview_clock.png")

font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
ascent, descent = font.getmetrics()
print(f"Font metrics: ascent={ascent}  descent={descent}")

# ── Render each glyph onto a large canvas, then crop ──────────────────────
# Use a large scratch image so nothing clips.
CANVAS = FONT_SIZE * 4
BX, BY = CANVAS // 2, CANVAS // 2 + ascent   # left-baseline anchor

glyphs = {}
for ch in CHARS:
    scratch = Image.new("L", (CANVAS, CANVAS), 0)
    d       = ImageDraw.Draw(scratch)
    # anchor='ls': left-baseline → anchor point is on the baseline
    bb = d.textbbox((BX, BY), ch, font=font, anchor='ls')
    d.text((BX, BY), ch, font=font, fill=255, anchor='ls')   # ← actually render
    x0, y0, x1, y1 = bb

    adv_w = int(font.getlength(ch))
    w, h  = x1 - x0, y1 - y0

    # LVGL ofs metrics (relative to pen position / baseline)
    ofs_x = x0 - BX
    ofs_y = BY - y1   # positive = bottom above baseline

    if w <= 0 or h <= 0:
        glyphs[ch] = dict(adv_w=adv_w, box_w=0, box_h=0,
                          ofs_x=0, ofs_y=0, bits=[])
        continue

    # Draw with the SAME anchor at the SAME position, then crop tightly
    img = scratch.crop((x0, y0, x1, y1))
    pixels = list(img.getdata())
    bits   = [1 if p >= 64 else 0 for p in pixels]
    glyphs[ch] = dict(adv_w=adv_w, box_w=w, box_h=h,
                      ofs_x=ofs_x, ofs_y=ofs_y, bits=bits)

# ── Pack bits MSB-first, NO per-row padding (LVGL v8 continuous stream) ───
# LVGL reads bit N as: byte[N>>3] >> (7-(N&7)) — rows are NOT padded to
# byte boundaries; the bit stream flows continuously across all rows.
def pack_bits(bits, w, h):
    out   = []
    byte  = 0
    count = 0
    for bit in bits:          # bits[] already in row-major order
        byte = (byte << 1) | bit
        count += 1
        if count == 8:
            out.append(byte)
            byte, count = 0, 0
    if count:                 # flush last partial byte
        out.append(byte << (8 - count))
    return out

bitmap_data, glyph_descs, bitmap_index = [], [], 0
char_order = list(CHARS)
for ch in char_order:
    g      = glyphs[ch]
    packed = pack_bits(g['bits'], g['box_w'], g['box_h']) if g['box_w'] else []
    glyph_descs.append(dict(bitmap_index=bitmap_index,
                            adv_w=g['adv_w'], box_w=g['box_w'], box_h=g['box_h'],
                            ofs_x=g['ofs_x'], ofs_y=g['ofs_y']))
    bitmap_data.extend(packed); bitmap_index += len(packed)

line_height = ascent + descent
base_line   = descent

# ── Write C file ──────────────────────────────────────────────────────────
lines = [
    "/*", " * font_clock_120.c  — auto-generated by tools/gen_clock_font.py",
    " * Arial Bold 120pt, chars: 0-9 and ':'  (1-bpp LVGL v8 format)",
    " * Do not edit by hand.", " */",
    '#include "lvgl.h"', "",
    "static const uint8_t font_clock_120_glyph_bitmap[] = {",
]
for i in range(0, len(bitmap_data), 16):
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap_data[i:i+16]) + ",")
lines += ["};", "",
          "static const lv_font_fmt_txt_glyph_dsc_t font_clock_120_glyph_dsc[] = {",
          "    {0},  /* [0] placeholder */"]
for i, ch in enumerate(char_order):
    g = glyph_descs[i]
    lines.append(f"    {{.bitmap_index = {g['bitmap_index']}, .adv_w = {g['adv_w']*16}, "
                 f".box_w = {g['box_w']}, .box_h = {g['box_h']}, "
                 f".ofs_x = {g['ofs_x']}, .ofs_y = {g['ofs_y']}}},  /* '{ch}' */")
lines += ["};", ""]

space_idx = char_order.index(' ') + 1
lines += [
    "static const lv_font_fmt_txt_cmap_t font_clock_120_cmaps[] = {",
    "    { .range_start=0x30, .range_length=11, .glyph_id_start=1,",
    "      .type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,",
    "      .unicode_list=NULL, .glyph_id_ofs_list=NULL, .list_length=0 },",
    "    { .range_start=0x20, .range_length=1, "
    f".glyph_id_start={space_idx},",
    "      .type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,",
    "      .unicode_list=NULL, .glyph_id_ofs_list=NULL, .list_length=0 },",
    "};", "",
    "static const lv_font_fmt_txt_dsc_t font_clock_120_dsc = {",
    "    .glyph_bitmap  = font_clock_120_glyph_bitmap,",
    "    .glyph_dsc     = font_clock_120_glyph_dsc,",
    "    .cmaps         = font_clock_120_cmaps,",
    "    .kern_dsc      = NULL, .kern_scale = 0,",
    "    .cmap_num      = 2, .bpp = 1,",
    "    .kern_classes  = 0, .bitmap_format = 0,",
    "};", "",
    "const lv_font_t font_clock_120 = {",
    "    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,",
    "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
    f"    .line_height      = {line_height},",
    f"    .base_line        = {base_line},",
    "    .subpx            = LV_FONT_SUBPX_NONE,",
    "    .underline_position  = -2, .underline_thickness = 1,",
    "    .dsc              = &font_clock_120_dsc,",
    "    .fallback         = &lv_font_montserrat_48,",
    "    .user_data        = NULL,",
    "};", "",
]
os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
with open(OUT_C, "w") as f:
    f.write("\n".join(lines))
print(f"Wrote {OUT_C}  ({len(bitmap_data)} bitmap bytes, {line_height}px line height)")

# ── Preview PNG ────────────────────────────────────────────────────────────
# Simulate the idle screen at 800×480
W, H = 800, 480
preview = Image.new("RGB", (W, H))
dp = ImageDraw.Draw(preview)

# Sky gradient (top dark blue → lighter blue)
for y in range(H):
    t = y / H
    r = int(0x13 + t * (0x49 - 0x13))
    g = int(0x44 + t * (0xA3 - 0x44))
    b = int(0x88 + t * (0xE0 - 0x88))
    dp.line([(0, y), (W, y)], fill=(r, g, b))

# Sun
dp.ellipse([544, 38, 640, 134], fill=(255, 213, 106))

# Overlay for readability
dp.rectangle([0, 0, W, H], fill=(6, 24, 47, 80))

# Load small fonts for preview
f14 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 14)
f16 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 16)
f18 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 18)
f20 = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 20)

# Header
dp.text((24, 16),  "LAWNBOT",            font=ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 24), fill=(248,251,255), anchor='lt')
dp.text((26, 48),  "BOISE STATE EDITION",font=f14,             fill=(241,99,34),  anchor='lt')
dp.text((W-24, 24),"DEMO MODE",          font=f14,             fill=(197,210,227),anchor='rt')

# Clock — draw using the actual baked glyphs (paste each glyph)
clock_text = "14:06"
pen_x = W // 2  # will center below
total_w = sum(glyphs[c]['adv_w'] + (4 if c != clock_text[-1] else 0) for c in clock_text)
pen_x = (W - total_w) // 2
pen_y_baseline = 80 + ascent  # y=80 is top of clock area

for ch in clock_text:
    g = glyphs[ch]
    if g['box_w'] > 0 and g['bits']:
        glyph_img = Image.new("RGBA", (g['box_w'], g['box_h']), (0,0,0,0))
        for row in range(g['box_h']):
            for col in range(g['box_w']):
                if g['bits'][row * g['box_w'] + col]:
                    glyph_img.putpixel((col, row), (248, 251, 255, 255))
        # ofs_x: horizontal offset from pen to glyph left
        # ofs_y: offset from baseline to glyph bottom → glyph top = baseline - box_h - ofs_y
        gx = pen_x + g['ofs_x']
        gy = pen_y_baseline - g['box_h'] - g['ofs_y']
        preview.paste(glyph_img, (gx, gy), glyph_img)
    pen_x += g['adv_w'] + 4  # 4px letter spacing

# Weather info lines
C_TEXT  = (248, 251, 255)
C_MUTED = (197, 210, 227)
C_ORA   = (241, 99, 34)
dp.text((W//2, 258), "Saturday  Mar 21",              font=f18, fill=C_MUTED, anchor='mt')
dp.text((W//2, 296), "CLEAR SKIES",                   font=f20, fill=C_TEXT,  anchor='mt')
dp.text((W//2, 332), "74 F  |  HUM 58%  |  WIND 7 MPH N", font=f16, fill=C_MUTED, anchor='mt')
dp.text((W//2, 362), "NEXT: HANGING POTS  07:00",     font=f14, fill=C_ORA,  anchor='mt')

# Bottom hint
dp.text((W//2, 440), "TOUCH SCREEN FOR CONTROLS",     font=f14, fill=C_MUTED, anchor='mt')

os.makedirs(os.path.dirname(OUT_PNG), exist_ok=True)
preview.save(OUT_PNG)
print(f"Preview saved: {OUT_PNG}")
print("\nGlyph summary:")
for ch, g in zip(char_order, glyph_descs):
    print(f"  '{ch}'  adv={g['adv_w']}  box={g['box_w']}x{g['box_h']}  ofs=({g['ofs_x']},{g['ofs_y']})")
